### ISSUE TITLE
Delta må håndtere slettede arrangementer

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#315]
```
En ukjent feil har oppstått i Delta! Debug-informasjon: 
Exception: An exception has been thrown during the rendering of a template ("MONSTRING_V2: _load_by_row krever dataarray!"). 
Route: /ukmid/ User: [...], ID: 21694 Debug backtrace: #0
```

Bare silently skip hvis dette skjer

**Comment by mariusmandal** [comment]
Varsle support:81981 når problemet er løst.

**Comment by AsgeirSH** [comment]
Tror det er denne som feiler:
```
[2020-01-16 09:23:51] app.ERROR: ExceptionListener: ERROR: Unhandled Exception occurred. Event-data:  {"event":"[object] (Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent: {})"} []
[2020-01-16 09:23:51] app.ERROR: ExceptionListener: Totalt ukjent. File: /ukmid/ [] []
[2020-01-16 09:23:51] app.INFO: UKMdelta: Notifying support of the issue [] []
[2020-01-16 09:23:51] app.ERROR: Trace data: array (   'message' => 'An exception has been thrown during the rendering of a template ("MONSTRING_V2: _load_by_row krever dataarray!").',   'file' => '/home/ukmdelta/public_html/src/UKMNorge/DeltaBundle/Resources/views/UKMID/innslag.html.twig',   
'line' => 3,   
'trace' => '#0 /home/ukmdelta/public_html/vendor/twig/twig/src/Template.php(422): Twig\\Template->displayWithErrorHandling(Array, Array) #1 /home/ukmdelta/cache/symfony/ukmdelta/prod/twig/27/27088d887b8df34b7b7697ad550a5cff592a4265d7616590d8dad1aed251eb7e.php(120): Twig\\Template->display(Array) #2 /home/ukmdelta/public_html/vendor/twig/twig/src/Template.php(216): 
[..]
/home/ukmdelta/public_html/src/UKMNorge/DeltaBundle/Controller/UKMIDController.php(48): 
Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller->render(\'UKMDeltaBundle:...\', Array) #28 /home/ukmdelta/public_html/var/bootstrap.php.cache(3276): 
UKMNorge\\DeltaBundle\\Controller\\UKMIDController->indexAction() #29 /home/ukmdelta/public_html/var/bootstrap.php.cache(3235): 
Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1) #30 
[...]
[2020-01-16 09:23:51] security.DEBUG: Stored the security token in the session. {"key":"_security_ukm_delta_wall"} []

```

**Comment by AsgeirSH** [comment]
En skikkelig fiks på dette ville kanskje vært å sørge for at innslaget blir meldt av ved sletting av arrangement? Delta prøver ikke å vise innslag med `b_status` > 8.

Men løser det nå med at Innslag\Samling::_load() ikke henter innslag der arrangementet ikke finnes.

**Comment by AsgeirSH** [comment]
Ehm... Fikk ikke til å reprodusere denne i .dev, da det i stedet dukker opp "SLETTET: Båtsfjord" som kommunenavn. Mener du når det er slettet helt? Evt relasjonen mellom arrangement og innslag er borte?

**Comment by AsgeirSH** [comment]
Se https://github.com/UKMNorge/UKMapi/pull/97 for mulig fiks.

**Comment by mariusmandal** [comment]
Trøbbelet kommer når vi prøver å hente arrangementet fra `smartukm_band`.`b_pl_home_id` og det arrangementet er sletta.
Arrangementer har også fått feltet `pl_deleted` (de slettes ikke lengre fullstendig fra databasen). Collection/Klassen (bør i alle fall) tar hensyn til dette feltet, og opprettelse kan feile selv om raden finnes i databasen
