### ISSUE TITLE
Oppretting av enkeltperson-innslag feiler i hentKontaktpersonInnslag

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#345]
```
#0 /etc/php-includes/UKM/Innslag/Samling.php(144): UKMNorge\Innslag\Samling->_load()
#1 /home/ukmdelta/public_html/src/UKMNorge/APIBundle/Services/InnslagService.php(235): UKMNorge\Innslag\Samling->getAll()
#2 /home/ukmdelta/public_html/src/UKMNorge/APIBundle/Services/InnslagService.php(205): UKMNorge\APIBundle\Services\InnslagService->hentInnslagFraKontaktperson('[***obfuscated***]')
#3 /home/ukmdelta/public_html/src/UKMNorge/DeltaBundle/Controller/InnslagController.php(236): UKMNorge\APIBundle\Services\InnslagService->hentEnkeltPersonInnslag(Object(UKMNorge\Innslag\Typer\Type), Object(UKMNorge\Arrangement\Arrangement), Object(UKMNorge\Innslag\Personer\Person))
#4 /home/ukmdelta/public_html/var/bootstrap.php.cache(3276): UKMNorge\DeltaBundle\Controller\InnslagController->createAction([***obfuscated***], 6097, Object(UKMNorge\Innslag\Typer\Type))
#5 /home/ukmdelta/public_html/var/bootstrap.php.cache(3235): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#6 /home/ukmdelta/public_html/var/bootstrap.php.cache(3389): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /home/ukmdelta/public_html/var/bootstrap.php.cache(2594): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /home/ukmdelta/public_html/web/app.php(27): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 {main}
```

**Comment by mariusmandal** [comment]
Feilen oppstår når kommunen har blitt slettet
