### ISSUE TITLE
Feil i uthenting av kontaktpersonens innslag

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#347]
**Exception:** 0
Call to a member function getId() on null

**Backtrace:**

#0 /etc/php-includes/UKM/Innslag/Samling.php(144): UKMNorge\Innslag\Samling->_load() 
#1 /home/ukmdelta/public_html/src/UKMNorge/APIBundle/Services/InnslagService.php(232): UKMNorge\Innslag\Samling->getAll() 
#2 /home/ukmdelta/public_html/src/UKMNorge/DeltaBundle/Controller/InnslagController.php(191): UKMNorge\APIBundle\Services\InnslagService->hentInnslagFraKontaktperson() 
#3 /home/ukmdelta/public_html/var/bootstrap.php.cache(3276): UKMNorge\DeltaBundle\Controller\InnslagController->fylkePreTypeAction(6421)

**Comment by mariusmandal** [comment]
Debug infos: 
 - brukeren eksisterer i delta, og har `pameld_user` satt
 - personen eksisterer i `participant`-tabellen
 - brukeren har påmeldte innslag fra tidligere år, men ingen i år
 - alle innslag fra 2020 har `b_home_pl` og `b_kommune` satt, mens tidligere år ikke har det
 - blant tidligere innslag, har minst ett innslag en deaktivert kommune i `b_kommune`-feltet

**Comment by mariusmandal** [comment]
Support #84377

**Comment by mariusmandal** [comment]
Testet OK hos Torstein
