### ISSUE TITLE
Uthenting av kontaktpersonens innslag feiler

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#349]
Lignende forløp som UKMNorge/UKMdelta#347

Debug-informasjon: 
Exception: 110002, Ukjent innslag-type 1 
Route: /ukmid/ 
User: E***e, ID: 9***
Pameld User: ****
Debug backtrace:
#0 /etc/php-includes/UKM/Innslag/Typer/Typer.php(324): UKMNorge\Innslag\Typer\Typer::_translate_id_to_key(1)
#1 /etc/php-includes/UKM/Innslag/Typer/Typer.php(142): UKMNorge\Innslag\Typer\Typer::load(1, '')
#2 /etc/php-includes/UKM/Innslag/Innslag.php(391): UKMNorge\Innslag\Typer\Typer::getById(1, '')
#3 /etc/php-includes/UKM/Innslag/Innslag.php(205): UKMNorge\Innslag\Innslag->setType('1', '')
#4 /etc/php-includes/UKM/Innslag/Innslag.php(93): UKMNorge\Innslag\Innslag->_loadByRow(Array)
#5 /etc/php-includes/UKM/Innslag/Samling.php(500): UKMNorge\Innslag\Innslag->__construct(Array, true)
#6 /etc/php-includes/UKM/Innslag/Samling.php(144): UKMNorge\Innslag\Samling->_load()
#7 /home/ukmdelta/public_html/src/UKMNorge/APIBundle/Services/InnslagService.php(232): UKMNorge\Innslag\Samling->getAll()
#8 /home/ukmdelta/public_html/src/UKMNorge/DeltaBundle/Controller/UKMIDController.php(45): UKMNorge\APIBundle\Services\InnslagService->hentInnslagFraKontaktperson()
#9 /home/ukmdelta/public_html/var/bootstrap.php.cache(3276): UKMNorge\DeltaBundle\Controller\UKMIDController->indexAction()
#10 /home/ukmdelta/public_html/var/bootstrap.php.cache(3235): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /home/ukmdelta/public_html/var/bootstrap.php.cache(3389): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home/ukmdelta/public_html/var/bootstrap.php.cache(2594): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /home/ukmdelta/public_html/web/app.php(27): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}

**Comment by mariusmandal** [comment]
**Debug infos:**

brukeren eksisterer i delta, og har `pameld_user` satt
personen eksisterer i `participant`-tabellen
brukeren har påmeldte innslag fra tidligere år, men også i år (#347 var det ingen innslag i år)
alle innslag fra 2020 og 2021 har `b_home_pl` og `b_kommune` satt, mens tidligere år ikke har det

! blant tidligere innslag, mangler to innslag en kommune i b_kommune-feltet
de samme to innslagene mangler også `b_kategori`, og har `b_type` = 1

**Comment by mariusmandal** [comment]
Support#84449
